name: readme-recursion
description: An action to create cool recursive READMEs for your Github profile
author: Daan Koning
branding:
  icon: 'image'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
        with:
          repository: 'daankoning/recursive-readme'
    - run: pip install -r requirements.txt
      shell: bash
    - run: python images.py
      shell: bash
        
