name: readme-recursion
description: An action to create cool recursive READMEs for your Github profile
author: Daan Koning
branding:
  icon: 'image'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - run: pip install -r selenium webdriver-manager
      shell: bash
    - run: python images.py
      shell: bash
        
